export interface Hook {
  id: number;
  template: string;
}

export const HOOKS: Hook[] = [
  { id: 1, template: "Diluar ekspektasi banget aku beli X… kirain bakal Y, ternyata…" },
  { id: 2, template: "Ternyata orang yang Z itu pakenya X…" },
  { id: 3, template: "Baru tau kalau ada X yang bisa Y…" },
  { id: 4, template: "Kok ada sih orang mau X, padahal Y…" },
  { id: 5, template: "Baru tau X ini dari kemarin, padahal berguna banget…" },
  { id: 6, template: "Ternyata banyak yang belum tau soal X…" },
  { id: 7, template: "Aku baru nyoba X kemarin, ternyata…" },
  { id: 8, template: "Please… jangan beli X kalau belum lihat ini…" },
  { id: 9, template: "Hari ini aku mau sharing pengalaman soal X…" },
  { id: 10, template: "Hari ini aku mau eksperimen, kalau X apakah Y?" },
  { id: 11, template: "Menurutku yang bikin X ini cukup menarik…" },
  { id: 12, template: "Lumayan repot juga gara-gara beli X…" },
  { id: 13, template: "Aku nemu 1 produk yang cocok buat Z…" },
  { id: 14, template: "Cukup bagus sih produk X ini…" },
  { id: 15, template: "Aku hampir kelewatan produk X ini…" },
  { id: 16, template: "Dulu aku pikir X itu Y, tapi sekarang beda…" },
  { id: 17, template: "Beginilah hasilnya setelah pakai X…" },
  { id: 18, template: "Aku beli X lagi karena…" },
  { id: 19, template: "Kalau kamu suka X, produk ini bisa jadi pilihan…" },
  { id: 20, template: "Ini dia X yang aku pakai sekarang…" },
  { id: 21, template: "Harga X ini cukup terjangkau menurutku…" },
  { id: 22, template: "Ini pengalaman aku pakai X…" },
  { id: 23, template: "Perlu diperhatikan kalau mau beli X, karena…" },
  { id: 24, template: "Produk X ini lumayan populer…" },
  { id: 25, template: "Kalau punya anak kecil, X ini bisa jadi pilihan…" },
  { id: 26, template: "Yang sering Y, bisa coba X…" },
  { id: 27, template: "Dalam jualan, harga mahal atau murah itu relatif tergantung nilai yang didapat…" },
  { id: 28, template: "Ada beberapa feedback tentang X ini…" },
  { id: 29, template: "Hari ini aku mau coba X dan sharing pengalaman…" },
  { id: 30, template: "Stop scrolling kalau lagi nyari X…" },
  { id: 31, template: "Produk kayak gini yang menarik buat dicoba…" },
  { id: 32, template: "Temen-temen penasaran sama X ini…" },
  { id: 33, template: "Sebenernya aku mau sharing pengalaman soal X…" },
  { id: 34, template: "X lagi… tapi kali ini ada yang beda…" },
  { id: 35, template: "Cukup hemat pakai X dibanding alternatif lain…" },
  { id: 36, template: "Kalau HP kamu support Y, X ini bisa jadi pilihan…" },
  { id: 37, template: "Nemu X yang harganya cukup bersaing…" },
  { id: 38, template: "Pernah ngalamin Y? Nah X ini bisa jadi solusi…" },
  { id: 39, template: "Hari ini aku mau bandingkan beberapa X…" },
  { id: 40, template: "Kalau mau Y, pertimbangkan pakai X…" },
  { id: 41, template: "Siapa tau kamu belum tau ada X kayak gini…" },
  { id: 42, template: "Ini pengalaman jujur aku soal X…" },
  { id: 43, template: "X ini punya kualitas yang cukup bagus…" },
  { id: 44, template: "Coba pertimbangkan X kalau lagi nyari produk sejenis…" },
  { id: 45, template: "Dengan budget terbatas, X ini bisa jadi pilihan…" },
  { id: 46, template: "X ini harganya cukup kompetitif…" },
  { id: 47, template: "Lagi ada promo untuk X…" },
  { id: 48, template: "Ini kabar baik buat yang sering Y…" },
  { id: 49, template: "Belum banyak yang tau ada X seperti ini…" },
  { id: 50, template: "Harga X ini cukup terjangkau untuk kualitasnya…" },
  { id: 51, template: "Coba pertimbangkan kualitas sebelum beli X…" },
  { id: 52, template: "Cara supaya Y nggak kejadian lagi: pertimbangkan X…" },
  { id: 53, template: "Dengan budget pas-pasan, ini bisa jadi solusi…" },
  { id: 54, template: "Kebiasaan yang bisa diperbaiki: Y, coba pakai X…" },
  { id: 55, template: "Kalau cocok sama kebutuhanmu, X ini bisa jadi pilihan…" },
  { id: 56, template: "Saatnya tes X ini, apakah sesuai klaim?" },
  { id: 57, template: "Pilih mana, sering bayar buat Y, atau investasi sekali untuk X?" },
  { id: 58, template: "Harga X ini cukup mengejutkan…" },
  { id: 59, template: "Diluar ekspektasi, X ini cukup terjangkau…" },
  { id: 60, template: "Kompetisi di kategori X ini cukup ketat…" },
  { id: 61, template: "Dari beberapa X yang aku coba, ini yang menurutku bagus…" },
  { id: 62, template: "Nggak tau kenapa tapi aku cukup suka X ini…" },
  { id: 63, template: "Harga terjangkau nggak selalu berarti kualitas jelek…" },
  { id: 64, template: "Sekarang Y jadi lebih mudah dengan X…" },
  { id: 65, template: "Siapa yang bisa lebih hemat dengan pakai X?" },
  { id: 66, template: "Gimana kalau X bisa membantu kamu Y?" },
  { id: 67, template: "Produk ini punya banyak review positif…" },
  { id: 68, template: "X ini punya kualitas yang kompetitif…" },
  { id: 69, template: "Kok bisa ada X dengan harga segini…" },
  { id: 70, template: "Pengalamanku pakai X cukup positif…" },
  { id: 71, template: "Menurutku X ini cukup membantu untuk Y…" },
  { id: 72, template: "Penasaran nggak kalau X bisa Y?" },
  { id: 73, template: "Gimana bisa ya X harganya segini…" },
  { id: 74, template: "Coba pertimbangkan X kalau kebutuhanmu seperti ini…" },
  { id: 75, template: "Apakah X bisa membantu kamu Y?" },
  { id: 76, template: "Nggak nyangka X segini harganya…" },
  { id: 77, template: "Contoh kalau produk bagus nggak harus mahal…" },
  { id: 78, template: "Kalau nemu X harga segini, bisa jadi kesempatan bagus…" },
  { id: 79, template: "Ada nggak sih X yang lebih bagus dari ini?" },
  { id: 80, template: "Pengalaman aku pakai X cukup menarik…" },
  { id: 81, template: "Anak-anak sepertinya suka X ini…" },
  { id: 82, template: "Menurutku X ini termasuk yang bagus di kategorinya…" },
  { id: 83, template: "Bisa jadi pilihan bagus buat kamu yang sering Y…" },
  { id: 84, template: "Gara-gara X, pengalaman Y jadi lebih baik…" },
  { id: 85, template: "Solusi buat kamu yang mau Y dengan budget terbatas…" },
  { id: 86, template: "Ternyata dengan X bisa membantu untuk…" },
  { id: 87, template: "Bisa menambah kenyamanan dengan X…" },
  { id: 88, template: "Coba pertimbangkan X sebelum terlambat…" },
  { id: 89, template: "X ini mulai banyak dipakai orang…" },
  { id: 90, template: "Waktu yang tepat buat coba X…" },
  { id: 91, template: "Kalau tau dari dulu ada X, mungkin aku nggak perlu repot Y…" },
  { id: 92, template: "Pengalaman aku dengan X cukup memuaskan…" },
  { id: 93, template: "Pernah nggak sih penasaran kenapa nggak coba X dari dulu?" },
  { id: 94, template: "Dengan budget terbatas, kamu bisa coba X ini…" },
  { id: 95, template: "Supaya Y nggak terulang, bisa coba pakai X…" },
  { id: 96, template: "Setelah coba beberapa X, ini yang aku rekomendasikan…" },
  { id: 97, template: "Bisa jadi pilihan kalau kamu sering Y…" },
  { id: 98, template: "Aku pikir X ini biasa aja, ternyata cukup bagus…" },
  { id: 99, template: "Kalau ada X, beberapa hal jadi lebih praktis…" },
  { id: 100, template: "Alternatif yang lebih baik dari Y adalah X…" },
  { id: 101, template: "Siapa bilang X mahal? Ini ada pilihan terjangkau…" },
  { id: 102, template: "Banyak alasan kenapa X layak dicoba…" },
  { id: 103, template: "Banyak orang sekarang beralih ke X…" },
  { id: 104, template: "X ini bisa jadi tambahan yang berguna di rumah…" },
  { id: 105, template: "Kalau kamu males ribet, X ini bisa jadi solusi…" },
  { id: 106, template: "Karena X, sekarang aku bisa Y dengan lebih mudah…" },
  { id: 107, template: "Yang jarang keluar rumah mungkin butuh X…" },
  { id: 108, template: "Beberapa orang kaget dengan harga X…" },
  { id: 109, template: "Akhirnya nemu juga X yang sesuai kebutuhan…" },
  { id: 110, template: "Tinggal pilih: tetap dengan cara lama atau coba X ini…" },
  { id: 111, template: "Kadang yang harganya terjangkau justru seperti X ini…" },
  { id: 112, template: "Setelah pakai X, pengalamannya cukup positif…" },
  { id: 113, template: "Ada yang masih ragu sama X?" },
  { id: 114, template: "Aku beliin X ini buat keluarga dan responnya positif…" },
  { id: 115, template: "Mau lebih hemat? Coba X…" },
  { id: 116, template: "Penawaran X dengan harga segini cukup menarik…" },
  { id: 117, template: "Aku tantang kamu coba X ini…" },
  { id: 118, template: "Gaya hidup hemat bisa dimulai dari X…" },
  { id: 119, template: "Yang belum nyoba mungkin belum paham nilai X…" },
  { id: 120, template: "Kualitas bagus dengan harga bersaing… itu X…" },
  { id: 121, template: "Kenapa nggak dari dulu aku coba X…" },
  { id: 122, template: "Awalnya ragu… tapi setelah coba X pengalamannya bagus…" },
  { id: 123, template: "X ini membantu aku untuk Y…" },
  { id: 124, template: "Jangan-jangan kamu belum tau ada X ini…" },
  { id: 125, template: "Mau Y tanpa ribet? Coba X…" },
  { id: 126, template: "Masalah Y jadi lebih jarang setelah pakai X…" },
  { id: 127, template: "Respon keluarga terhadap X ini positif…" },
  { id: 128, template: "Kalau tau ada X dari dulu, mungkin lebih praktis…" },
  { id: 129, template: "Pengalaman pakai X cukup modern…" },
  { id: 130, template: "Bayangin aja, X ini harganya segini…" },
  { id: 131, template: "Siapa yang tertarik dengan X harga segini…" },
  { id: 132, template: "Belum pernah nemu X yang bisa Y seperti ini…" },
  { id: 133, template: "Banyak yang bilang X ini worth it mencoba…" },
  { id: 134, template: "Investasi sekali, manfaat jangka panjang… itu X…" },
  { id: 135, template: "X ini bisa jadi tambahan yang berguna…" },
  { id: 136, template: "Biarpun harganya terjangkau, X ini kualitasnya lumayan…" },
  { id: 137, template: "Awalnya aku ragu, tapi ternyata X ini oke…" },
  { id: 138, template: "Solusi hemat waktu dan tenaga? Coba X…" },
  { id: 139, template: "Jangan nunda, coba X sekarang…" },
  { id: 140, template: "Kalau ada pilihan produk terbaik, aku pilih X…" },
  { id: 141, template: "Pengalaman pakai X terus positif…" },
  { id: 142, template: "Cukup sekali coba untuk tau kualitas X…" },
  { id: 143, template: "Banyak yang nyoba X dan kasih review bagus…" },
  { id: 144, template: "Beberapa hal jadi lebih mudah gara-gara X…" },
  { id: 145, template: "Kadang solusi datang dari produk seperti X…" },
  { id: 146, template: "Sering Y? Coba pertimbangkan X…" },
  { id: 147, template: "Yang aku butuhin tersedia di X ini…" },
  { id: 148, template: "Pertimbangkan apakah kamu butuh X…" },
  { id: 149, template: "Bukan cuma bagus, X ini juga praktis…" },
  { id: 150, template: "Banyak yang nyoba dan memberikan feedback positif…" },
  { id: 151, template: "Sejak ada X, pengalaman Y jadi lebih baik…" },
  { id: 152, template: "Ini alasan kenapa banyak orang pilih X…" },
  { id: 153, template: "X ini cukup berkualitas…" },
  { id: 154, template: "Awalnya cuma iseng beli X, sekarang jadi langganan…" },
  { id: 155, template: "Siapa sangka X bisa bikin beberapa hal lebih simpel…" },
  { id: 156, template: "Agak kurang nyaman kalau kehabisan X…" },
  { id: 157, template: "Nggak nyangka X bisa jadi solusi untuk Y…" },
  { id: 158, template: "Banyak rumah tangga yang terbantu dengan X ini…" },
  { id: 159, template: "Setelah pakai, kamu bakal paham kenapa X ini populer…" },
  { id: 160, template: "Harga segini untuk X? Cukup kompetitif…" },
  { id: 161, template: "Jangan sampai kehabisan, coba X sekarang…" },
  { id: 162, template: "Banyak orang yang Z memilih X ini…" },
  { id: 163, template: "Aku sharing pengalamanku: X…" },
  { id: 164, template: "X ini jadi produk andalan aku…" },
  { id: 165, template: "Awalnya cuma coba-coba, eh ternyata cocok sama X…" },
  { id: 166, template: "Penawaran X dengan harga ini cukup menarik…" },
  { id: 167, template: "Beberapa orang kaget X ini bisa Y…" },
  { id: 168, template: "Banyak review yang sejalan tentang X…" },
  { id: 169, template: "Aku beli X ini setelah pertimbangan…" },
  { id: 170, template: "Jangan remehkan X, ini bisa sangat membantu…" },
  { id: 171, template: "Pengalaman dengan X ini cukup unik…" },
  { id: 172, template: "Banyak orang perlu tau soal X ini…" },
  { id: 173, template: "Awalnya males, sekarang lebih rajin gara-gara X membantu…" },
  { id: 174, template: "Kalau kamu mau lebih hemat, pertimbangkan X…" },
  { id: 175, template: "Produk seperti X ini jarang ada promo…" },
  { id: 176, template: "Pengalaman dengan X sejauh ini positif…" },
  { id: 177, template: "Banyak yang setuju X ini bagus…" },
  { id: 178, template: "Aku rekomendasikan X ini buat kamu…" },
  { id: 179, template: "X ini membantu aku jadi lebih efisien…" },
  { id: 180, template: "Banyak yang liat X ini langsung tertarik…" },
  { id: 181, template: "Sejak punya X, beberapa hal jadi lebih mudah…" },
  { id: 182, template: "Pengalaman aku dengan X cukup memuaskan…" },
  { id: 183, template: "Setiap kali pakai X, hasilnya konsisten…" },
  { id: 184, template: "X ini cocok buat yang sering Y…" },
  { id: 185, template: "Awalnya nggak ngerti kegunaan X, sekarang paham manfaatnya…" },
  { id: 186, template: "Mau hidup lebih praktis? Coba X…" },
  { id: 187, template: "Banyak yang tau X dan kasih review positif…" },
  { id: 188, template: "X ini jadi bagian rutinitas aku…" },
  { id: 189, template: "Nggak nyangka produk sekompak X bisa seefektif ini…" },
  { id: 190, template: "Masalah Y lebih mudah ditangani dengan X…" },
  { id: 191, template: "Aku prefer pakai X dibanding cara lama…" },
  { id: 192, template: "Kadang solusi cukup sederhana dengan X…" },
  { id: 193, template: "Yang Z mungkin butuh X ini…" },
  { id: 194, template: "Kalau nggak mau repot, pertimbangkan X…" },
  { id: 195, template: "X ini bikin aku lebih produktif untuk Y…" },
  { id: 196, template: "Aku cukup puas dengan X ini…" },
  { id: 197, template: "X ini membantu pengeluaran jadi lebih efisien…" },
  { id: 198, template: "Yang udah coba pasti paham nilai X…" },
  { id: 199, template: "Sekarang aku paham kenapa X ini populer…" },
  { id: 200, template: "Mau hidup lebih santai? X bisa membantu…" },
];
