// laranganBank.ts
export interface LaranganRule {
  dilarang: string;
  ganti: string;
}

export const LARANGAN_RULES: LaranganRule[] = [
  { dilarang: 'terbaik', ganti: 'salah satu yang disukai banyak orang' },
  { dilarang: 'nomor 1', ganti: 'termasuk produk favorit' },
  { dilarang: 'paling ampuh', ganti: 'bekerja sesuai kebutuhan' },
  { dilarang: 'paling cepat', ganti: 'hasil tiap orang berbeda' },
  { dilarang: 'paling efektif', ganti: 'bantu memaksimalkan penggunaan' },
  { dilarang: 'paling murah', ganti: 'harganya ramah kantong' },
  { dilarang: 'termurah', ganti: 'harga termasuk terjangkau' },
  { dilarang: 'paling lengkap', ganti: 'fiturnya cukup lengkap' },
  { dilarang: 'paling bagus', ganti: 'kualitasnya rapi dan nyaman' },
  { dilarang: 'hasil instan', ganti: 'hasil bisa berbeda-beda' },
  { dilarang: 'hasil permanen', ganti: 'hasil tergantung pemakaian' },
  { dilarang: 'garansi pasti berhasil', ganti: 'cocok untuk banyak orang' },
  { dilarang: '100% berhasil', ganti: 'bantu mengoptimalkan fungsi' },
  { dilarang: '100% aman', ganti: 'lebih nyaman digunakan' },
  { dilarang: 'anti gagal', ganti: 'banyak review positif' },
  { dilarang: 'jaminan berhasil', ganti: 'bantu mempermudah aktivitas' },
  { dilarang: 'wajib punya', ganti: 'cocok buat yang butuh produk ini' },
  { dilarang: 'must have', ganti: 'bisa jadi pilihan menarik' },
  { dilarang: 'termurah se-', ganti: 'salah satu opsi ekonomis' },
  { dilarang: 'paling murah di TikTok', ganti: 'harganya kompetitif' },
  { dilarang: 'harga paling rendah', ganti: 'harganya cukup masuk akal' },
  { dilarang: 'banting harga', ganti: 'penawaran menarik' },
  { dilarang: 'murah banget', ganti: 'harganya bersahabat' },
  { dilarang: 'diskon terbesar', ganti: 'promo yang lumayan membantu' },
  { dilarang: 'harga tercantik', ganti: 'harga cukup oke' },
  { dilarang: 'kurus', ganti: 'lebih ringan' },
  { dilarang: 'gemuk', ganti: 'berisi' },
  { dilarang: 'obesitas', ganti: 'berat di atas rata-rata' },
  { dilarang: 'tirus', ganti: 'bentuk wajah lebih ramping' },
  { dilarang: 'pipi tembem', ganti: 'pipi lebih penuh' },
  { dilarang: 'pipi chubby', ganti: 'pipi lebih penuh' },
  { dilarang: 'berat badan', ganti: 'bobot tubuh' },
  { dilarang: 'menurunkan berat badan', ganti: 'bantu mengelola bobot' },
  { dilarang: 'menaikkan berat badan', ganti: 'bantu memenuhi kebutuhan nutrisi' },
  { dilarang: 'mengecilkan perut', ganti: 'bantu merapikan area perut' },
  { dilarang: 'mengecilkan lengan', ganti: 'bantu memperindah tampilan lengan' },
  { dilarang: 'membesarkan bokong', ganti: 'memberi efek lebih berisi' },
  { dilarang: 'membesarkan payudara', ganti: 'memberi efek lebih penuh' },
  { dilarang: 'mengecilkan paha', ganti: 'bantu merapikan area paha' },
  { dilarang: 'tinggi badan', ganti: 'postur tubuh' },
  { dilarang: 'menambah tinggi', ganti: 'bantu mendukung postur' },
  { dilarang: 'tubuh ideal', ganti: 'tubuh yang nyaman buat kamu' },
  { dilarang: 'tubuh sempurna', ganti: 'versi terbaik dari diri sendiri' },
  { dilarang: 'langsing instan', ganti: 'tampilan lebih ramping' },
  { dilarang: 'menyembuhkan', ganti: 'membantu meredakan' },
  { dilarang: 'mengobati', ganti: 'membantu mengurangi ketidaknyamanan' },
  { dilarang: 'terapi', ganti: 'perawatan sederhana di rumah' },
  { dilarang: 'menyembuhkan penyakit', ganti: 'mendukung aktivitas harian' },
  { dilarang: 'bebas penyakit', ganti: 'menjaga kebersihan' },
  { dilarang: 'obat kuat', ganti: 'suplemen penunjang' },
  { dilarang: 'obat pelangsing', ganti: 'produk pendukung diet' },
  { dilarang: 'obat pemutih', ganti: 'produk pencerah' },
  { dilarang: 'memutihkan', ganti: 'mencerahkan bertahap' },
  { dilarang: 'mencerahkan permanen', ganti: 'efek cerah yang konsisten bila rutin' },
  { dilarang: 'whitening permanen', ganti: 'bantu menjaga kecerahan' },
  { dilarang: 'aman untuk ibu hamil', ganti: 'konsultasikan dulu bila perlu' },
  { dilarang: 'aman untuk menyusui', ganti: 'gunakan sesuai kebutuhan' },
  { dilarang: 'untuk bayi baru lahir', ganti: 'cocok untuk usia tertentu' },
  { dilarang: 'cocok untuk anak-anak', ganti: 'baca petunjuk penggunaan' },
  { dilarang: 'jelek', ganti: 'kurang rapi' },
  { dilarang: 'item kulit', ganti: 'kulit kurang merata' },
  { dilarang: 'kusam parah', ganti: 'kulit kurang cerah' },
  { dilarang: 'muka rusak', ganti: 'kulit sedang tidak stabil' },
  { dilarang: 'muka berantakan', ganti: 'kulit lagi kurang bagus' },
  { dilarang: 'wajah hancur', ganti: 'kulit butuh perhatian' },
  { dilarang: 'bodoh', ganti: 'kurang tepat' },
  { dilarang: 'tolol', ganti: 'kurang efektif' },
  { dilarang: 'instan', ganti: 'bekerja perlahan' },
  { dilarang: 'seketika', ganti: 'terlihat lebih cepat pada sebagian orang' },
  { dilarang: 'permanen', ganti: 'bisa bertahan lama bila rutin' },
  { dilarang: 'menghilangkan jerawat 100%', ganti: 'membantu merawat kulit berjerawat' },
  { dilarang: 'menghilangkan noda hitam', ganti: 'membantu menyamarkan noda' },
  { dilarang: 'glowing instan', ganti: 'memberikan tampilan lebih fresh' },
  { dilarang: 'berubah drastis', ganti: 'lebih rapi/smooth' },
  { dilarang: 'transformasi ekstrem', ganti: 'perubahan lebih terlihat' },
  { dilarang: 'keranjang kuning', ganti: 'keranjang bawah' },
  { dilarang: 'keranjang oren', ganti: 'keranjang bawah' },
];

// Build a compact rule string for the system prompt
export const buildLaranganPrompt = (): string => {
  const lines = LARANGAN_RULES.map(r => `"${r.dilarang}" → ganti dengan "${r.ganti}"`);
  return `ATURAN KALIMAT AMAN — WAJIB DIPATUHI. Kata/frasa berikut DILARANG digunakan, ganti dengan alternatif yang tertera:\n${lines.join('\n')}`;
};
